version: '4.2'

services:
    nginx:
        image: nginx:alpine
        container_name: webhooks-nginx
        volumes:
            - ../../../:/var/www/app
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - webhooks

    intranet:
        container_name: webhooks-intranet
        build: .
        volumes:
            - ../../../:/var/www/app
        working_dir: /var/www/app
        networks:
            - webhooks

networks:
    webhooks:
        external: true
